import { z } from 'zod';
import {
  AgentHqApiClient,
  VALID_TASK_PRIORITIES,
  VALID_TASK_STATUSES,
  VALID_TASK_STORY_POINTS,
  VALID_TASK_TYPES,
} from './apiClient';
import { registerCatalogTool } from './catalog';

function add(names: string[], description: string, schema: Record<string, z.ZodTypeAny>, domain: string, rest_paths?: string[]) {
  registerCatalogTool({ names, description, schema, domain, rest_paths });
}

export function registerAgentHqMcpCatalog(_api = new AgentHqApiClient('http://127.0.0.1')) {
  const storyPointsSchema = z
    .union(
      VALID_TASK_STORY_POINTS.map((value) => z.literal(value)) as [
        z.ZodLiteral<1>,
        z.ZodLiteral<2>,
        z.ZodLiteral<3>,
        z.ZodLiteral<5>,
        z.ZodLiteral<8>,
        z.ZodLiteral<13>,
        z.ZodLiteral<21>,
      ],
    )
    .nullable()
    .optional();

  const workflowStatusSchema = z.object({
    status_key: z.string().min(1).describe('Status key'),
    label: z.string().min(1).describe('Status label'),
    color: z.string().optional().describe('Status color'),
    stage_order: z.number().int().min(0).describe('Display order'),
    terminal: z.union([z.boolean(), z.number().int()]).optional().describe('Terminal status flag'),
    is_default_entry: z.union([z.boolean(), z.number().int()]).optional().describe('Default entry flag'),
    metadata: z.record(z.string(), z.unknown()).optional().describe('Optional metadata'),
  });

  const workflowTransitionSchema = z.object({
    from_status_key: z.string().min(1).describe('From status key'),
    to_status_key: z.string().min(1).describe('To status key'),
    transition_key: z.string().min(1).describe('Transition key'),
    label: z.string().min(1).describe('Transition label'),
    outcome: z.string().nullable().optional().describe('Optional mapped outcome'),
    stage_order: z.number().int().min(0).describe('Display order'),
    metadata: z.record(z.string(), z.unknown()).optional().describe('Optional metadata'),
  });

  add(['agent_hq_get_projects', 'atlas_get_projects', 'agent_hq_list_projects', 'atlas_list_projects'], 'List Agent HQ projects with clean summary fields.', {}, 'projects', ['/api/v1/projects']);
  add(['agent_hq_get_project', 'atlas_get_project'], 'Get a project by ID, including metrics.', { project_id: z.number().int().positive().describe('Project ID') }, 'projects', ['/api/v1/projects/:id']);
  add(['agent_hq_create_project', 'atlas_create_project'], 'Create a project in Agent HQ.', { name: z.string().min(1).describe('Project name'), description: z.string().optional().describe('Project description'), context_md: z.string().optional().describe('Project context markdown') }, 'projects', ['/api/v1/projects']);
  add(['agent_hq_update_project', 'atlas_update_project'], 'Update a project in Agent HQ.', { project_id: z.number().int().positive().describe('Project ID'), name: z.string().min(1).optional().describe('Project name'), description: z.string().optional().describe('Project description'), context_md: z.string().optional().describe('Project context markdown') }, 'projects', ['/api/v1/projects/:id']);
  add(['agent_hq_delete_project', 'atlas_delete_project'], 'Delete a project. Returns truthful validation errors when active work blocks deletion unless force=true is passed.', { project_id: z.number().int().positive().describe('Project ID'), force: z.boolean().optional().describe('Force delete even if active work exists') }, 'projects', ['/api/v1/projects/:id']);

  add(['agent_hq_get_sprints', 'atlas_get_sprints', 'agent_hq_list_sprints', 'atlas_list_sprints'], 'List Agent HQ sprints. Optionally filter by project.', { project_id: z.number().int().positive().optional().describe('Filter by project ID'), include_closed: z.boolean().optional().describe('Include closed sprints (default false)') }, 'sprints', ['/api/v1/sprints']);
  add(['agent_hq_get_sprint', 'atlas_get_sprint'], 'Get sprint detail and metrics.', { sprint_id: z.number().int().positive().describe('Sprint ID') }, 'sprints', ['/api/v1/sprints/:id']);
  add(['agent_hq_create_sprint', 'atlas_create_sprint'], 'Create a new sprint in Agent HQ, with optional dry-run preview.', { project_id: z.number().int().positive().describe('Project ID (required)'), name: z.string().min(1).describe('Sprint name (required)'), goal: z.string().optional().describe('Sprint goal'), sprint_type: z.string().optional().describe('Sprint type key'), workflow_template_key: z.string().nullable().optional().describe('Workflow template key'), status: z.enum(['planning', 'active', 'paused', 'complete', 'closed']).optional().describe('Initial sprint status'), length_kind: z.enum(['time', 'runs']).optional().describe('Sprint length kind'), length_value: z.string().optional().describe('Sprint length value, e.g. 2w or 10'), started_at: z.string().nullable().optional().describe('Sprint start timestamp'), dry_run: z.boolean().optional().describe('Return a mutation preview without writing data') }, 'sprints', ['/api/v1/sprints']);
  add(['agent_hq_update_sprint', 'atlas_update_sprint'], 'Update a sprint in Agent HQ. Project reassignment is passed through truthfully and will fail clearly if the backend rejects it.', { sprint_id: z.number().int().positive().describe('Sprint ID'), project_id: z.number().int().positive().optional().describe('Optional project reassignment request'), name: z.string().min(1).optional().describe('Sprint name'), goal: z.string().optional().describe('Sprint goal'), sprint_type: z.string().optional().describe('Sprint type key'), workflow_template_key: z.string().nullable().optional().describe('Workflow template key'), status: z.enum(['planning', 'active', 'paused', 'complete', 'closed']).optional().describe('Sprint status'), length_kind: z.enum(['time', 'runs']).optional().describe('Sprint length kind'), length_value: z.string().optional().describe('Sprint length value'), started_at: z.string().nullable().optional().describe('Sprint start timestamp'), ended_at: z.string().nullable().optional().describe('Sprint end timestamp') }, 'sprints', ['/api/v1/sprints/:id']);
  add(['agent_hq_delete_sprint', 'atlas_delete_sprint'], 'Delete a sprint in Agent HQ.', { sprint_id: z.number().int().positive().describe('Sprint ID') }, 'sprints', ['/api/v1/sprints/:id']);

  add(['agent_hq_get_tasks', 'atlas_get_tasks', 'agent_hq_list_tasks', 'atlas_list_tasks'], 'List Agent HQ tasks with optional filtering.', { project_id: z.number().int().positive().optional().describe('Filter by project ID'), sprint_id: z.number().int().positive().optional().describe('Filter by sprint ID'), status: z.string().optional().describe('Task status filter'), limit: z.number().int().min(1).max(100).optional().describe('Max results (default 50, max 100)'), offset: z.number().int().min(0).optional().describe('Pagination offset (default 0)') }, 'tasks', ['/api/v1/tasks']);
  add(['agent_hq_get_task_detail', 'atlas_get_task_detail', 'agent_hq_get_task', 'atlas_get_task'], 'Get full task detail including blocker, sprint, and assignment context.', { task_id: z.number().int().positive().describe('Task ID') }, 'tasks', ['/api/v1/tasks/:id']);
  add(['agent_hq_create_task', 'atlas_create_task'], 'Create a new task in Agent HQ, with optional assignment, blockers, and dry-run preview.', { title: z.string().min(1).describe('Task title (required)'), project_id: z.number().int().positive().describe('Project ID (required)'), description: z.string().optional().describe('Task description (markdown supported)'), sprint_id: z.number().int().positive().nullable().optional().describe('Sprint ID to place the task in'), priority: z.enum(VALID_TASK_PRIORITIES).optional().describe('Priority (default: medium)'), task_type: z.enum(VALID_TASK_TYPES).optional().describe('Task type (default: backend)'), story_points: storyPointsSchema.describe('Story points: 1, 2, 3, 5, 8, 13, or 21'), agent_id: z.number().int().positive().nullable().optional().describe('Assign the task to an agent'), blockers: z.array(z.number().int().positive()).optional().describe('Task IDs that block this task'), dry_run: z.boolean().optional().describe('Return a mutation preview without writing data') }, 'tasks', ['/api/v1/tasks']);
  add(['agent_hq_update_task', 'atlas_update_task'], 'Update editable fields on an existing task, including sprint and assignment, with optional dry-run preview.', { task_id: z.number().int().positive().describe('Task ID (required)'), title: z.string().min(1).optional().describe('New title'), description: z.string().optional().describe('New description'), priority: z.enum(VALID_TASK_PRIORITIES).optional().describe('New priority'), sprint_id: z.number().int().positive().nullable().optional().describe('Move to a different sprint, or null to clear'), task_type: z.enum(VALID_TASK_TYPES).optional().describe('New task type'), story_points: storyPointsSchema.describe('New story point estimate'), agent_id: z.number().int().positive().nullable().optional().describe('Assign to a different agent, or null to clear'), dry_run: z.boolean().optional().describe('Return a mutation preview without writing data') }, 'tasks', ['/api/v1/tasks/:id']);
  add(['agent_hq_move_task', 'atlas_move_task'], 'Move a task to a new status. Uses outcome semantics for gated workflow states and supports dry-run preview.', { task_id: z.number().int().positive().describe('Task ID (required)'), status: z.enum(VALID_TASK_STATUSES).describe('Target status (required)'), summary: z.string().optional().describe('Optional summary for outcome-based moves'), review_branch: z.string().optional().describe('Review branch for review transition'), review_commit: z.string().optional().describe('Review commit for review transition'), review_url: z.string().optional().describe('Review URL for review transition'), qa_verified_commit: z.string().optional().describe('QA verified commit for qa_pass transition'), qa_tested_url: z.string().optional().describe('QA tested URL for qa_pass transition'), merged_commit: z.string().optional().describe('Merged commit for deployed transition'), deployed_commit: z.string().optional().describe('Deployed commit for deployed/done transition'), deploy_target: z.string().optional().describe('Deploy target for deployed transition'), deployed_at: z.string().optional().describe('Deploy timestamp for deployed transition'), live_verified_by: z.string().optional().describe('Verifier identity for done transition'), live_verified_at: z.string().optional().describe('Verification timestamp for done transition'), failure_class: z.string().optional().describe('Failure class when moving through a failed outcome'), failure_detail: z.string().optional().describe('Failure detail when moving through a failed outcome'), dry_run: z.boolean().optional().describe('Return a mutation preview without writing data') }, 'tasks', ['/api/v1/tasks/:id', '/api/v1/tasks/:id/outcome']);
  add(['agent_hq_delete_task', 'atlas_delete_task'], 'Delete a task from Agent HQ.', { task_id: z.number().int().positive().describe('Task ID'), deleted_by: z.string().optional().describe('Audit label for the delete operation') }, 'tasks', ['/api/v1/tasks/:id']);
  add(['agent_hq_get_task_notes', 'atlas_get_task_notes'], 'Get notes/comments for a task.', { task_id: z.number().int().positive().describe('Task ID') }, 'tasks', ['/api/v1/tasks/:id/notes']);
  add(['agent_hq_get_task_history', 'atlas_get_task_history'], 'Get task history entries for a task.', { task_id: z.number().int().positive().describe('Task ID') }, 'tasks', ['/api/v1/tasks/:id/history']);
  add(['agent_hq_add_task_note', 'atlas_add_task_note'], 'Add a note or comment to a task.', { task_id: z.number().int().positive().describe('Task ID (required)'), content: z.string().min(1).describe('Note content (required)'), author: z.string().optional().describe('Author label (default: mcp-client)') }, 'tasks', ['/api/v1/tasks/:id/notes']);
  add(['agent_hq_add_blocker', 'atlas_add_blocker'], 'Mark a task as blocked by another task, with optional dry-run preview.', { task_id: z.number().int().positive().describe('The task to mark as blocked (required)'), blocked_by_task_id: z.number().int().positive().describe('The task that is blocking it (required)'), dry_run: z.boolean().optional().describe('Return a mutation preview without writing data') }, 'tasks', ['/api/v1/tasks/:id/blockers']);
  add(['agent_hq_remove_blocker', 'atlas_remove_blocker'], 'Remove a blocker relationship from a task.', { task_id: z.number().int().positive().describe('The blocked task (required)'), blocker_id: z.number().int().positive().describe('The blocker record ID to remove (required)') }, 'tasks', ['/api/v1/tasks/:id/blockers/:blockerId']);

  add(['agent_hq_list_routing_rules', 'atlas_list_routing_rules'], 'List task routing rules for a sprint.', { sprint_id: z.number().int().positive().describe('Sprint ID') }, 'routing_rules', ['/api/v1/routing/rules', '/api/v1/routing-rules']);
  add(['agent_hq_get_routing_rule', 'atlas_get_routing_rule'], 'Get a single task routing rule by ID within a sprint.', { rule_id: z.number().int().positive().describe('Routing rule ID'), sprint_id: z.number().int().positive().describe('Sprint ID') }, 'routing_rules', ['/api/v1/routing/rules/:id', '/api/v1/routing-rules/:id']);
  add(['agent_hq_create_routing_rule', 'atlas_create_routing_rule'], 'Create a task routing rule for a sprint.', { sprint_id: z.number().int().positive().describe('Sprint ID'), task_type: z.enum(VALID_TASK_TYPES).describe('Task type'), status: z.string().min(1).describe('Task status'), agent_id: z.number().int().positive().optional().describe('Canonical agent target'), job_id: z.number().int().positive().optional().describe('Legacy compat alias for agent_id'), priority: z.number().int().optional().describe('Rule priority') }, 'routing_rules', ['/api/v1/routing/rules', '/api/v1/routing-rules']);
  add(['agent_hq_update_routing_rule', 'atlas_update_routing_rule'], 'Update a task routing rule for a sprint.', { rule_id: z.number().int().positive().describe('Routing rule ID'), sprint_id: z.number().int().positive().describe('Sprint ID'), task_type: z.enum(VALID_TASK_TYPES).optional().describe('Task type'), status: z.string().min(1).optional().describe('Task status'), agent_id: z.number().int().positive().optional().describe('Canonical agent target'), job_id: z.number().int().positive().optional().describe('Legacy compat alias for agent_id'), priority: z.number().int().optional().describe('Rule priority') }, 'routing_rules', ['/api/v1/routing/rules/:id', '/api/v1/routing-rules/:id']);
  add(['agent_hq_delete_routing_rule', 'atlas_delete_routing_rule'], 'Delete a task routing rule from a sprint.', { rule_id: z.number().int().positive().describe('Routing rule ID'), sprint_id: z.number().int().positive().describe('Sprint ID') }, 'routing_rules', ['/api/v1/routing/rules/:id', '/api/v1/routing-rules/:id']);

  add(['agent_hq_list_routing_transitions', 'atlas_list_routing_transitions'], 'List canonical routing transitions used for model/workflow routing.', { sprint_id: z.number().int().positive().optional().describe('Optional sprint scope'), project_id: z.number().int().positive().optional().describe('Optional project scope') }, 'routing_transitions', ['/api/v1/routing/transitions']);
  add(['agent_hq_get_routing_transition', 'atlas_get_routing_transition'], 'Get a canonical routing transition by ID.', { transition_id: z.number().int().positive().describe('Transition ID'), sprint_id: z.number().int().positive().optional().describe('Optional sprint scope'), project_id: z.number().int().positive().optional().describe('Optional project scope') }, 'routing_transitions', ['/api/v1/routing/transitions/:id']);
  add(['agent_hq_create_routing_transition', 'atlas_create_routing_transition'], 'Create a canonical routing transition.', { sprint_id: z.number().int().positive().optional().describe('Optional sprint scope'), project_id: z.number().int().positive().optional().describe('Optional project scope'), task_type: z.enum(VALID_TASK_TYPES).nullable().optional().describe('Optional task type scope'), from_status: z.string().min(1).describe('From status'), outcome: z.string().min(1).describe('Outcome key'), to_status: z.string().min(1).describe('To status'), lane: z.string().optional().describe('Lane label'), enabled: z.boolean().optional().describe('Enabled flag'), priority: z.number().int().optional().describe('Priority'), is_protected: z.boolean().optional().describe('Protected flag for sprint-scoped rules') }, 'routing_transitions', ['/api/v1/routing/transitions']);
  add(['agent_hq_update_routing_transition', 'atlas_update_routing_transition'], 'Update a canonical routing transition.', { transition_id: z.number().int().positive().describe('Transition ID'), sprint_id: z.number().int().positive().optional().describe('Optional sprint scope'), project_id: z.number().int().positive().optional().describe('Optional project scope'), task_type: z.enum(VALID_TASK_TYPES).nullable().optional().describe('Optional task type scope'), from_status: z.string().min(1).optional().describe('From status'), outcome: z.string().min(1).optional().describe('Outcome key'), to_status: z.string().min(1).optional().describe('To status'), lane: z.string().optional().describe('Lane label'), enabled: z.boolean().optional().describe('Enabled flag'), priority: z.number().int().optional().describe('Priority'), is_protected: z.boolean().optional().describe('Protected flag for sprint-scoped rules') }, 'routing_transitions', ['/api/v1/routing/transitions/:id']);
  add(['agent_hq_delete_routing_transition', 'atlas_delete_routing_transition'], 'Delete a canonical routing transition.', { transition_id: z.number().int().positive().describe('Transition ID'), sprint_id: z.number().int().positive().optional().describe('Optional sprint scope') }, 'routing_transitions', ['/api/v1/routing/transitions/:id']);

  add(['agent_hq_list_model_routing_rules', 'atlas_list_model_routing_rules'], 'List story-point model-routing rules.', {}, 'model_routing', ['/api/v1/model-routing', '/api/v1/story-point-routing']);
  add(['agent_hq_get_model_routing_rule', 'atlas_get_model_routing_rule'], 'Get a story-point model-routing rule by ID.', { rule_id: z.number().int().positive().describe('Model-routing rule ID') }, 'model_routing', ['/api/v1/model-routing/:id', '/api/v1/story-point-routing/:id']);
  add(['agent_hq_create_model_routing_rule', 'atlas_create_model_routing_rule'], 'Create a story-point model-routing rule.', { max_points: z.number().int().positive().describe('Max story points threshold'), provider: z.string().optional().describe('Model provider'), model: z.string().min(1).describe('Primary model'), fallback_model: z.string().nullable().optional().describe('Fallback model'), max_turns: z.number().int().positive().nullable().optional().describe('Max turns'), max_budget_usd: z.number().nullable().optional().describe('Budget cap'), thinking_level: z.enum(['off', 'minimal', 'low', 'medium', 'high', 'adaptive']).nullable().optional().describe('Optional reasoning effort override'), label: z.string().nullable().optional().describe('Rule label') }, 'model_routing', ['/api/v1/model-routing', '/api/v1/story-point-routing']);
  add(['agent_hq_update_model_routing_rule', 'atlas_update_model_routing_rule'], 'Update a story-point model-routing rule.', { rule_id: z.number().int().positive().describe('Model-routing rule ID'), max_points: z.number().int().positive().optional().describe('Max story points threshold'), provider: z.string().optional().describe('Model provider'), model: z.string().min(1).optional().describe('Primary model'), fallback_model: z.string().nullable().optional().describe('Fallback model'), max_turns: z.number().int().positive().nullable().optional().describe('Max turns'), max_budget_usd: z.number().nullable().optional().describe('Budget cap'), thinking_level: z.enum(['off', 'minimal', 'low', 'medium', 'high', 'adaptive']).nullable().optional().describe('Optional reasoning effort override'), label: z.string().nullable().optional().describe('Rule label') }, 'model_routing', ['/api/v1/model-routing/:id', '/api/v1/story-point-routing/:id']);
  add(['agent_hq_delete_model_routing_rule', 'atlas_delete_model_routing_rule'], 'Delete a story-point model-routing rule.', { rule_id: z.number().int().positive().describe('Model-routing rule ID') }, 'model_routing', ['/api/v1/model-routing/:id', '/api/v1/story-point-routing/:id']);

  add(['agent_hq_list_sprint_types', 'atlas_list_sprint_types'], 'List sprint types.', {}, 'task_definitions', ['/api/v1/sprints/types/list', '/api/v1/task-definitions/sprint-types']);
  add(['agent_hq_list_sprint_type_task_types', 'atlas_list_sprint_type_task_types'], 'List allowed task types for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key') }, 'task_definitions', ['/api/v1/sprints/types/:key/task-types', '/api/v1/task-definitions/sprint-types/:key/task-types']);
  add(['agent_hq_update_sprint_type_task_types', 'atlas_update_sprint_type_task_types'], 'Replace the allowed task types for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), task_types: z.array(z.string().min(1)).describe('Allowed task type keys') }, 'task_definitions', ['/api/v1/sprints/types/:key/task-types', '/api/v1/task-definitions/sprint-types/:key/task-types']);
  add(['agent_hq_create_sprint_type', 'atlas_create_sprint_type'], 'Create a sprint type.', { key: z.string().min(1).describe('Sprint type key'), name: z.string().min(1).describe('Sprint type name'), description: z.string().optional().describe('Sprint type description') }, 'task_definitions', ['/api/v1/sprints/types', '/api/v1/task-definitions/sprint-types']);
  add(['agent_hq_update_sprint_type', 'atlas_update_sprint_type'], 'Update a sprint type.', { key: z.string().min(1).describe('Sprint type key'), name: z.string().min(1).optional().describe('Sprint type name'), description: z.string().optional().describe('Sprint type description') }, 'task_definitions', ['/api/v1/sprints/types/:key', '/api/v1/task-definitions/sprint-types/:key']);
  add(['agent_hq_delete_sprint_type', 'atlas_delete_sprint_type'], 'Delete a sprint type.', { key: z.string().min(1).describe('Sprint type key') }, 'task_definitions', ['/api/v1/sprints/types/:key', '/api/v1/task-definitions/sprint-types/:key']);
  add(['agent_hq_list_workflow_templates', 'atlas_list_workflow_templates'], 'List workflow templates, optionally filtered by sprint type.', { sprint_type: z.string().optional().describe('Optional sprint type key') }, 'task_definitions', ['/api/v1/sprints/workflow-templates', '/api/v1/workflow-templates']);
  add(['agent_hq_get_workflow_template', 'atlas_get_workflow_template'], 'Get a workflow template for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), template_id: z.number().int().positive().describe('Template ID') }, 'task_definitions', ['/api/v1/sprints/types/:key/workflow-templates/:templateId', '/api/v1/task-definitions/sprint-types/:key/workflow-templates/:templateId']);
  add(['agent_hq_create_workflow_template', 'atlas_create_workflow_template'], 'Create a workflow template for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), key: z.string().min(1).describe('Template key'), name: z.string().min(1).describe('Template name'), description: z.string().optional().describe('Template description'), is_default: z.union([z.boolean(), z.number().int()]).optional().describe('Default template flag'), statuses: z.array(workflowStatusSchema).min(1).describe('Workflow statuses'), transitions: z.array(workflowTransitionSchema).min(1).describe('Workflow transitions') }, 'task_definitions', ['/api/v1/sprints/types/:key/workflow-templates', '/api/v1/task-definitions/sprint-types/:key/workflow-templates']);
  add(['agent_hq_update_workflow_template', 'atlas_update_workflow_template'], 'Update a workflow template for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), template_id: z.number().int().positive().describe('Template ID'), key: z.string().min(1).optional().describe('Template key'), name: z.string().min(1).optional().describe('Template name'), description: z.string().optional().describe('Template description'), is_default: z.union([z.boolean(), z.number().int()]).optional().describe('Default template flag'), statuses: z.array(workflowStatusSchema).optional().describe('Workflow statuses'), transitions: z.array(workflowTransitionSchema).optional().describe('Workflow transitions') }, 'task_definitions', ['/api/v1/sprints/types/:key/workflow-templates/:templateId', '/api/v1/task-definitions/sprint-types/:key/workflow-templates/:templateId']);
  add(['agent_hq_delete_workflow_template', 'atlas_delete_workflow_template'], 'Delete a workflow template from a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), template_id: z.number().int().positive().describe('Template ID') }, 'task_definitions', ['/api/v1/sprints/types/:key/workflow-templates/:templateId', '/api/v1/task-definitions/sprint-types/:key/workflow-templates/:templateId']);
  add(['agent_hq_list_task_field_schemas', 'atlas_list_task_field_schemas'], 'List task field schemas for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key') }, 'task_definitions', ['/api/v1/sprints/types/:key/field-schemas', '/api/v1/task-definitions/sprint-types/:key/field-schemas']);
  add(['agent_hq_get_task_field_schema', 'atlas_get_task_field_schema'], 'Get a task field schema for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), schema_id: z.number().int().positive().describe('Schema ID') }, 'task_definitions', ['/api/v1/sprints/types/:key/field-schemas/:schemaId', '/api/v1/task-definitions/sprint-types/:key/field-schemas/:schemaId']);
  add(['agent_hq_create_task_field_schema', 'atlas_create_task_field_schema'], 'Create a task field schema for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), task_type: z.string().nullable().optional().describe('Optional task type scope'), schema: z.record(z.string(), z.unknown()).describe('Field schema payload') }, 'task_definitions', ['/api/v1/sprints/types/:key/field-schemas', '/api/v1/task-definitions/sprint-types/:key/field-schemas']);
  add(['agent_hq_update_task_field_schema', 'atlas_update_task_field_schema'], 'Update a task field schema for a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), schema_id: z.number().int().positive().describe('Schema ID'), task_type: z.string().nullable().optional().describe('Optional task type scope'), schema: z.record(z.string(), z.unknown()).optional().describe('Field schema payload') }, 'task_definitions', ['/api/v1/sprints/types/:key/field-schemas/:schemaId', '/api/v1/task-definitions/sprint-types/:key/field-schemas/:schemaId']);
  add(['agent_hq_delete_task_field_schema', 'atlas_delete_task_field_schema'], 'Delete a task field schema from a sprint type.', { sprint_type_key: z.string().min(1).describe('Sprint type key'), schema_id: z.number().int().positive().describe('Schema ID') }, 'task_definitions', ['/api/v1/sprints/types/:key/field-schemas/:schemaId', '/api/v1/task-definitions/sprint-types/:key/field-schemas/:schemaId']);

  add(['agent_hq_list_agent_skills', 'atlas_list_agent_skills'], 'List skill assignments for an agent as a first-class relation.', { agent_id: z.number().int().positive().describe('Agent ID') }, 'skills', ['/api/v1/agents/:id/skills']);
  add(['agent_hq_assign_skill_to_agent', 'atlas_assign_skill_to_agent'], 'Assign a skill to an agent as a first-class relation by skill id or skill name.', { agent_id: z.number().int().positive().describe('Agent ID'), skill_id: z.number().int().positive().optional().describe('Skill ID'), skill_name: z.string().min(1).optional().describe('Skill name') }, 'skills', ['/api/v1/agents/:id/skills']);
  add(['agent_hq_remove_skill_from_agent', 'atlas_remove_skill_from_agent'], 'Remove a skill assignment from an agent as a first-class relation by skill id or skill name.', { agent_id: z.number().int().positive().describe('Agent ID'), skill_id: z.number().int().positive().optional().describe('Skill ID'), skill_name: z.string().min(1).optional().describe('Skill name') }, 'skills', ['/api/v1/agents/:id/skills/:skillIdentifier']);

  add(['agent_hq_list_agents', 'atlas_list_agents'], 'List registered agents in Agent HQ.', {}, 'agents', ['/api/v1/agents']);
  add(['agent_hq_list_jobs', 'atlas_list_jobs'], 'List agents (formerly jobs). Optionally filter by project.', { project_id: z.number().int().positive().optional().describe('Filter by project ID') }, 'agents', ['/api/v1/agents']);
  add(['agent_hq_get_agent', 'atlas_get_agent'], 'Get a single agent by ID.', { agent_id: z.number().int().positive().describe('Agent ID') }, 'agents', ['/api/v1/agents/:id']);
  add(['agent_hq_create_agent', 'atlas_create_agent'], 'Create a new agent.', { name: z.string().min(1).describe('Agent name'), role: z.string().optional().describe('Role label'), session_key: z.string().optional().describe('Session key for openclaw agents'), workspace_path: z.string().optional().describe('Workspace path'), repo_path: z.string().nullable().optional().describe('Canonical local git repo path for worktree mode'), repo_url: z.string().nullable().optional().describe('Remote git URL for clone mode'), repo_access_mode: z.enum(['worktree', 'clone']).nullable().optional().describe('Explicit repo source mode'), status: z.string().optional().describe('Initial status'), provision_openclaw: z.boolean().optional().describe('Provision an OpenClaw-native agent'), runtime_type: z.string().optional().describe('Runtime type'), runtime_config: z.unknown().optional().describe('Runtime config object'), project_id: z.number().int().positive().nullable().optional().describe('Project association'), preferred_provider: z.string().nullable().optional().describe('Preferred model provider'), model: z.string().nullable().optional().describe('Preferred model'), system_role: z.string().nullable().optional().describe('Reserved built-in system role') }, 'agents', ['/api/v1/agents']);
  add(['agent_hq_update_agent', 'atlas_update_agent'], 'Update an agent. Any provided field is passed through to the Agent HQ API.', { agent_id: z.number().int().positive().describe('Agent ID'), patch: z.record(z.string(), z.unknown()).describe('Partial update payload') }, 'agents', ['/api/v1/agents/:id']);
  add(['agent_hq_delete_agent', 'atlas_delete_agent'], 'Delete an agent by ID.', { agent_id: z.number().int().positive().describe('Agent ID') }, 'agents', ['/api/v1/agents/:id']);
  add(['agent_hq_get_agent_docs', 'atlas_get_agent_docs'], 'Read the docs bundle for an agent workspace.', { agent_id: z.number().int().positive().describe('Agent ID') }, 'agents', ['/api/v1/agents/:id/docs']);
  add(['agent_hq_sync_agent_mcp', 'atlas_sync_agent_mcp'], 'Force re-materialization of the effective OpenClaw MCP config for an agent workspace.', { agent_id: z.number().int().positive().describe('Agent ID'), working_directory: z.string().optional().describe('Optional working directory override') }, 'agents', ['/api/v1/agents/:id/mcp/sync']);

  add(['agent_hq_list_skills', 'atlas_list_skills'], 'List Atlas-managed skills.', {}, 'skills', ['/api/v1/skills']);
  add(['agent_hq_get_skill', 'atlas_get_skill'], 'Get a skill by name.', { name: z.string().min(1).describe('Skill name') }, 'skills', ['/api/v1/skills/:name']);
  add(['agent_hq_create_skill', 'atlas_create_skill'], 'Create a new Atlas-managed skill.', { name: z.string().min(1).describe('Skill name'), description: z.string().optional().describe('Optional description'), content: z.string().optional().describe('SKILL.md content') }, 'skills', ['/api/v1/skills']);
  add(['agent_hq_update_skill', 'atlas_update_skill'], "Replace a skill's SKILL.md content.", { name: z.string().min(1).describe('Skill name'), content: z.string().min(1).describe('New SKILL.md content') }, 'skills', ['/api/v1/skills/:name']);
  add(['agent_hq_delete_skill', 'atlas_delete_skill'], 'Delete an Atlas-managed skill.', { name: z.string().min(1).describe('Skill name') }, 'skills', ['/api/v1/skills/:name']);

  add(['agent_hq_list_tools', 'atlas_list_tools'], 'List all Atlas HQ tools in the registry.', {}, 'tools', ['/api/v1/tools']);
  add(['agent_hq_get_tool', 'atlas_get_tool'], 'Get a tool definition by ID.', { tool_id: z.number().int().positive().describe('Tool ID') }, 'tools', ['/api/v1/tools/:id']);
  add(['agent_hq_create_tool', 'atlas_create_tool'], 'Create a tool in the Atlas HQ registry.', { name: z.string().min(1).describe('Tool name'), slug: z.string().min(1).describe('Unique tool slug'), description: z.string().optional().describe('Tool description'), implementation_type: z.string().min(1).describe('Implementation type'), implementation_body: z.string().optional().describe('Implementation body'), input_schema: z.unknown().optional().describe('JSON schema object'), permissions: z.string().optional().describe('Permission label'), tags: z.array(z.string()).optional().describe('Tool tags'), enabled: z.boolean().optional().describe('Enabled flag') }, 'tools', ['/api/v1/tools']);
  add(['agent_hq_update_tool', 'atlas_update_tool'], 'Update an Atlas HQ tool definition.', { tool_id: z.number().int().positive().describe('Tool ID'), patch: z.record(z.string(), z.unknown()).describe('Partial update payload') }, 'tools', ['/api/v1/tools/:id']);
  add(['agent_hq_delete_tool', 'atlas_delete_tool'], 'Soft-delete an Atlas HQ tool.', { tool_id: z.number().int().positive().describe('Tool ID') }, 'tools', ['/api/v1/tools/:id']);
  add(['agent_hq_test_tool', 'atlas_test_tool'], 'Run a tool test with sample input.', { tool_id: z.number().int().positive().describe('Tool ID'), input: z.record(z.string(), z.unknown()).describe('Sample tool input object') }, 'tools', ['/api/v1/tools/:id/test']);
  add(['agent_hq_list_agent_tools', 'atlas_list_agent_tools'], 'List all tools assigned to an agent.', { agent_id: z.number().int().positive().describe('Agent ID') }, 'tools', ['/api/v1/agents/:id/tools']);
  add(['agent_hq_assign_tool_to_agent', 'atlas_assign_tool_to_agent'], 'Assign a registry tool to an agent.', { agent_id: z.number().int().positive().describe('Agent ID'), tool_id: z.number().int().positive().describe('Tool ID'), overrides: z.record(z.string(), z.unknown()).optional().describe('Assignment overrides'), enabled: z.boolean().optional().describe('Assignment enabled flag') }, 'tools', ['/api/v1/agents/:id/tools']);
  add(['agent_hq_remove_tool_from_agent', 'atlas_remove_tool_from_agent'], 'Remove a tool assignment from an agent.', { agent_id: z.number().int().positive().describe('Agent ID'), tool_id: z.number().int().positive().describe('Tool ID') }, 'tools', ['/api/v1/agents/:id/tools/:toolId']);

  add(['agent_hq_list_mcp_servers', 'atlas_list_mcp_servers'], 'List MCP servers in the Atlas HQ registry.', {}, 'mcp_servers', ['/api/v1/mcp-servers']);
  add(['agent_hq_get_mcp_server', 'atlas_get_mcp_server'], 'Get an MCP server by ID.', { mcp_server_id: z.number().int().positive().describe('MCP server ID') }, 'mcp_servers', ['/api/v1/mcp-servers/:id']);
  add(['agent_hq_create_mcp_server', 'atlas_create_mcp_server'], 'Create an MCP server entry.', { name: z.string().min(1).describe('Display name'), slug: z.string().min(1).describe('Unique slug'), description: z.string().optional().describe('Description'), transport: z.string().optional().describe('Transport, currently stdio'), command: z.string().min(1).describe('Executable path'), args: z.array(z.string()).optional().describe('Command args'), env: z.record(z.string(), z.string()).optional().describe('Environment variables'), cwd: z.string().optional().describe('Working directory'), enabled: z.boolean().optional().describe('Enabled flag') }, 'mcp_servers', ['/api/v1/mcp-servers']);
  add(['agent_hq_update_mcp_server', 'atlas_update_mcp_server'], 'Update an MCP server entry.', { mcp_server_id: z.number().int().positive().describe('MCP server ID'), patch: z.record(z.string(), z.unknown()).describe('Partial update payload') }, 'mcp_servers', ['/api/v1/mcp-servers/:id']);
  add(['agent_hq_delete_mcp_server', 'atlas_delete_mcp_server'], 'Disable an MCP server entry.', { mcp_server_id: z.number().int().positive().describe('MCP server ID') }, 'mcp_servers', ['/api/v1/mcp-servers/:id']);
  add(['agent_hq_list_agent_mcp_servers', 'atlas_list_agent_mcp_servers'], 'List MCP servers assigned to an agent.', { agent_id: z.number().int().positive().describe('Agent ID') }, 'mcp_servers', ['/api/v1/agents/:id/mcp-servers']);
  add(['agent_hq_assign_mcp_server_to_agent', 'atlas_assign_mcp_server_to_agent'], 'Assign an MCP server to an agent.', { agent_id: z.number().int().positive().describe('Agent ID'), mcp_server_id: z.number().int().positive().describe('MCP server ID'), overrides: z.record(z.string(), z.unknown()).optional().describe('Assignment overrides'), enabled: z.boolean().optional().describe('Assignment enabled flag') }, 'mcp_servers', ['/api/v1/agents/:id/mcp-servers']);
  add(['agent_hq_remove_mcp_server_from_agent', 'atlas_remove_mcp_server_from_agent'], 'Remove an MCP server assignment from an agent.', { agent_id: z.number().int().positive().describe('Agent ID'), mcp_server_id: z.number().int().positive().describe('MCP server ID') }, 'mcp_servers', ['/api/v1/agents/:id/mcp-servers/:mcpServerId']);

  add(['agent_hq_api_request', 'atlas_api_request'], 'Advanced JSON-only Agent HQ REST request tool. Path must start with /api/v1/. Use this when no typed MCP tool exists yet.', { method: z.enum(['GET', 'POST', 'PUT', 'DELETE']).describe('HTTP method'), path: z.string().min(1).describe('Absolute API path starting with /api/v1/'), body: z.unknown().optional().describe('Optional JSON body for POST/PUT requests') }, 'advanced', ['/api/v1/*']);
}
